CREATE TABLE IF NOT EXISTS `food`.`dishes` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `dishname` VARCHAR(200) NULL DEFAULT NULL,
  `cuisine` VARCHAR(50) NULL DEFAULT NULL,
  `typeofmeal` VARCHAR(50) NULL DEFAULT NULL,
  `price` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8